language: csharp
mono: none
solution: MicroPipes.sln
dotnet: 2.0.3
dist: trusty
script:
- dotnet restore
- dotnet build ./cssrc/MicroPipes/MicroPipes.csproj -f netstandard2.0
- dotnet build ./src/MicroPipes.Schema/MicroPipes.fsproj -f netstandard2.0
- dotnet build ./tests/SyntaxTests/SyntaxTests.csproj 
