version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

clone_depth: 5

configuration: Release

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
- cmd: dotnet restore 

build_script:
  
- cmd: dotnet build 