version: 1.0.{build}

#branches:
#  only:
#    - cs-master

image: Visual Studio 2017

clone_depth: 5

configuration: Release

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore 

build_script:
  - cmd: dotnet build 

#test_script:
  # run the unit tests (requires changing into the test directory)
  #- cmd: cd tests
  #- cmd: cd MicroPipes.Tests
  #- cmd: dotnet run