version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

clone_depth: 5

configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: HeavePipe.sln      # path to Visual Studio solution or project